# Generated by Django 3.1.7 on 2023-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=100)),
                ('apartamento', models.CharField(max_length=80)),
                ('habitaciones', models.CharField(max_length=60)),
                ('propietario', models.CharField(max_length=60)),
                ('banos', models.CharField(max_length=50)),
            ],
        ),
    ]
